{% set name = "mne-faster" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbe483517dcd286e53a4450f01b1c364cca4a41d3ce499e3e1987c584354ba51

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - mne-base

test:
  imports:
    - mne_faster
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wmvanvliet/mne-faster
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This implements the FASTER pipeline using MNE-Python

extra:
  recipe-maintainers:
    - wmvanvliet
    - hoechenberger
    - larsoner
