{% set name = "mne-faster" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b66726e39995623dff57f7a83f03d955c9ae06de40fa1d4770cd09f3f91f2be0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - mne-base

test:
  imports:
    - mne_faster
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/wmvanvliet/mne-faster
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This implements the FASTER pipeline using MNE-Python

extra:
  recipe-maintainers:
    - wmvanvliet
    - hoechenberger
    - larsoner
